on:
  pull_request:
    branches:
      - master
name: Pull Request Pipeline
jobs:
  pull_request_pipeline:
    name: Pull Request Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-db
        with:
            path: ~/.symfony/cache
            key: db
      - uses: symfonycorp/security-checker-action@v4
